### ISSUE TITLE
How are split moves performed?

### ISSUE THREAD

**Issue by 1ethanhansen** [ayushidubal/quantum-algorithms#30]
I'm trying to play with a friend and we can't find how to perform a split move in the game. How is that done?

**Comment by ayushidubal** [comment]
Hi Ethan
The shift key toggles between quantum and classical modes. 
To perform a split, press shift once, and select the piece you want to move. Select the first position you want to place the piece at, and then select the second position. You have now moved the piece to two different position with a 50% chance of the piece being measured in each spot. Hope this helps!

**Comment by 1ethanhansen** [comment]
@ayushidubal thanks! that helps :)
